export const TEST_QUESTION_COUNT = 20;

export const QUESTION_BANK = [
  {
    id: "foundation-suiton-reine",
    section: "Fondations",
    diff: 1,
    pts: 1,
    q: "Quelle nature de chakra règne à Kiri, considérée comme la « reine » du village ?",
    choices: ["Katon", "Suiton", "Fūton", "Doton"],
    answer: 1,
  },
  {
    id: "foundation-monde-invisible",
    section: "Fondations",
    diff: 1,
    pts: 1,
    q: "L'Art Sensoriel reconnaît 7 sens : les 5 fondamentaux, l'Instinct (6e), et ___ (7e).",
    choices: ["L'âme ancestrale", "Le Monde de l'Invisible", "L'écho du chakra", "La voix des abysses"],
    answer: 1,
  },
  {
    id: "foundation-mudras-majeurs",
    section: "Fondations",
    diff: 1,
    pts: 1,
    q: "« Joindre les doigts, c'est rappeler au monde que le silence est une arme. » Combien de mudrās majeurs existent ?",
    choices: ["7", "10", "12", "13"],
    answer: 2,
  },
  {
    id: "weapons-saya-tensho",
    section: "Armes & Forges",
    diff: 1,
    pts: 1,
    q: "La Saya Naginata fut forgée en hommage à un samouraï tragique, pour offrir une voie aux sans-clan. Qui était-il ?",
    choices: ["Daizo Kurokaze", "Saya Tensho", "Mizugami Hoshigaki", "Kazuyori Karatachi"],
    answer: 1,
  },
  {
    id: "weapons-lame-noire-nature",
    section: "Armes & Forges",
    diff: 2,
    pts: 2,
    q: "La Lame Noire, originelle du Pays du Vent, chante quand un orage approche. Quelle nature de chakra dort dans son noyau ?",
    choices: ["Raiton", "Fūton", "Katon", "Suiton"],
    answer: 1,
  },
  {
    id: "weapons-jashin-faux-activation",
    section: "Armes & Forges",
    diff: 2,
    pts: 2,
    q: "Comment un adepte de Jashin active-t-il le lien miroir avec sa victime via la faux à 3 lames ?",
    choices: [
      "Il trace un sceau dans le sang de la victime",
      "Il prononce une prière à Jashin trois fois",
      "Il lèche la lame après y avoir versé son sang",
      "Il transperce sa propre paume avec la faux",
    ],
    answer: 2,
  },
  {
    id: "weapons-kusarigama-forgeur",
    section: "Armes & Forges",
    diff: 2,
    pts: 2,
    q: "Qui a forgé la Kusarigama empoisonnée — chaîne et faucille dont chaque maillon peut être enduit de poison ?",
    choices: ["Madara Uchiha", "Daizo Kurokaze", "Habizumo Kirizami", "Mizugami Hoshigaki"],
    answer: 1,
  },
  {
    id: "weapons-nozarashi",
    section: "Armes & Forges",
    diff: 3,
    pts: 3,
    q: "Une lame samouraï imbibée de sang séché, qui semble respirer et ne s'éveille qu'au contact d'un véritable combattant — laquelle est-ce ?",
    choices: ["Tenshiken", "Hana no Ken", "Nozarashi", "Saya Naginata"],
    answer: 2,
  },
  {
    id: "weapons-jashin-double-action",
    section: "Armes & Forges",
    diff: 3,
    pts: 3,
    q: "Lien Jashin scellé : le porteur frappe la victime au sabre dans la main droite tout en se taillant volontairement la main gauche. Que subit la victime ?",
    choices: [
      "Uniquement les dégâts du sabre direct",
      "Uniquement le miroir — le sabre est annulé",
      "Le miroir ET les dégâts du sabre, simultanément",
      "Le lien rituel est rompu par la double action",
    ],
    answer: 2,
  },
  {
    id: "clans-hozuki-suika",
    section: "Clans de la Brume",
    diff: 1,
    pts: 1,
    q: "Quel Kekkei Genkai définit le clan Hōzuki, leur permettant de liquéfier leur chair entière ?",
    choices: ["Kirisogan", "Suika no Jutsu", "Hyōton", "Mokuton"],
    answer: 1,
  },
  {
    id: "clans-karatachi-kirisogan",
    section: "Clans de la Brume",
    diff: 1,
    pts: 1,
    q: "Quelle pupille unique du clan Karatachi perce la brume la plus dense et permet d'en manipuler la densité ?",
    choices: ["Byakugan", "Kirisogan", "Shōton", "Meiton"],
    answer: 1,
  },
  {
    id: "clans-academie-hoshigaki",
    section: "Clans de la Brume",
    diff: 2,
    pts: 2,
    q: "Quel clan dirige l'Académie de Kirigakure, transmettant la philosophie de la Brume Sanglante ?",
    choices: ["Hōzuki", "Karatachi", "Hoshigaki", "Yokushin"],
    answer: 2,
  },
  {
    id: "clans-yokushin-hozuki",
    section: "Clans de la Brume",
    diff: 2,
    pts: 2,
    q: "Les Yokushin — « chiens de brume » sans noms propres — appartiennent corps et âme à quel clan ?",
    choices: ["Karatachi", "Hoshigaki", "Hōzuki", "Aucun — ils sont libres"],
    answer: 2,
  },
  {
    id: "clans-hoshigaki-requins-blancs",
    section: "Clans de la Brume",
    diff: 3,
    pts: 3,
    q: "Un Hoshigaki d'une patience infinie qui frappe d'un seul coup chirurgical, sans un mot. À quelle lignée de son clan appartient-il ?",
    choices: ["Requins Noirs", "Requins Blancs", "Lignée Yokushin", "Lignée Karatachi"],
    answer: 1,
  },
  {
    id: "clans-kazuyori-rang",
    section: "Clans de la Brume",
    diff: 3,
    pts: 3,
    q: "Kazuyori Karatachi, le « Faucheur de la Brume », gouverna durant l'ère la plus sombre. Quel rang occupait-il parmi les Mizukage ?",
    choices: ["2ᵉ Mizukage", "4ᵉ Mizukage", "7ᵉ Mizukage", "12ᵉ Mizukage"],
    answer: 1,
  },
  {
    id: "genjutsu-zone-crepusculaire",
    section: "Courants du Genjutsu",
    diff: 2,
    pts: 2,
    q: "En Zone Crépusculaire (Jagetsu Hōzuki), le Genjutsu agit sur l'interprétation, pas sur la perception brute. Que vit la cible ?",
    choices: [
      "Elle voit normalement et raisonne clairement",
      "Elle voit mais interprète de façon déformée et perd ses repères",
      "Elle est totalement aveuglée par l'illusion",
      "Elle voit avec une acuité amplifiée",
    ],
    answer: 1,
  },
  {
    id: "genjutsu-fuinjutsu-piliers",
    section: "Courants du Genjutsu",
    diff: 3,
    pts: 3,
    q: "Un scelleur maîtrise parfaitement son Shodō et son chakra, mais son esprit est troublé par des émotions violentes. Selon les 3 piliers du Fūinjutsu, qu'arrivera-t-il à ses sceaux ?",
    choices: [
      "Ils seront parfaits — la technique compense l'esprit",
      "Ils seront instables — un esprit troublé engendre des sceaux instables",
      "Le chakra explosera immédiatement à l'écriture",
      "Ils seront plus puissants grâce à l'intensité émotionnelle",
    ],
    answer: 1,
  },
  {
    id: "genjutsu-shakuton-douleur",
    section: "Courants du Genjutsu",
    diff: 4,
    pts: 5,
    q: "Un médecin-ninja attaque un Maître du Genjutsu au Shakuton (chaleur interne, évaporation des fluides, sans contact). Le Maître devrait être protégé par son architecture mentale — pourquoi cela le brise-t-il quand même ?",
    choices: [
      "Le Shakuton désactive les tenketsu et empêche tout Genjutsu",
      "Le Shakuton est immunisé contre le Genjutsu par nature élémentaire",
      "La souffrance interne du Shakuton fissure l'architecture mentale via la « douleur »",
      "Le Shakuton paralyse les mudrās nécessaires à la résistance",
    ],
    answer: 2,
  },
  {
    id: "reasoning-kuroi-kaminari",
    section: "Raisonnement",
    diff: 2,
    pts: 2,
    q: "« Le Kuroi Kaminari est au Raiton classique ce que la Zone Abyssale est à la Zone Lumineuse. » Que doit-on en conclure ?",
    choices: [
      "Le Kuroi Kaminari est une version affaiblie du Raiton",
      "Le Kuroi Kaminari transcende le Raiton, comme l'Abyssale dépasse la Lumineuse",
      "Les deux sont identiques, juste de couleurs différentes",
      "Le Kuroi Kaminari est l'élément opposé du Raiton",
    ],
    answer: 1,
  },
  {
    id: "reasoning-mugen-karatachi",
    section: "Raisonnement",
    diff: 3,
    pts: 3,
    q: "Les Karatachi méprisent le clan Mugen de Suna, qualifié de « parodies sans honneur ». Sachant que les Karatachi sont maîtres de l'assassinat silencieux, quelle est la cause LOGIQUE de ce mépris ?",
    choices: [
      "Les Mugen ont trahi un pacte ancien avec Kiri",
      "Les Mugen tentent d'imiter l'art de l'ombre des Karatachi",
      "Les Mugen ont assassiné un Mizukage Karatachi",
      "Les Mugen possèdent un Kekkei Genkai similaire au Kirisogan",
    ],
    answer: 1,
  },
  {
    id: "reasoning-habizumo-prothese",
    section: "Raisonnement",
    diff: 4,
    pts: 4,
    q: "La prothèse d'Habizumo connecte des tenketsu synthétiques au moignon, MAIS ne remplace pas les terminaisons nerveuses détruites. Quelle conséquence LOGIQUE pour l'utilisateur ?",
    choices: [
      "La prothèse est inutilisable en combat",
      "L'utilisateur doit acquérir une maîtrise fine du chakra pour piloter le bras",
      "Le bras ne fonctionne qu'avec une infusion constante de Suiton",
      "L'utilisateur perd toute sensation dans son autre bras",
    ],
    answer: 1,
  },
  {
    id: "finale-mizugami-chronologie",
    section: "Épreuve Finale",
    diff: 4,
    pts: 8,
    q: "Mizugami Hoshigaki, le « Démon de la Brume », fut sensei de Yogetsu Hōzuki, assassina le 6ᵉ Mizukage Reigetsu, et fut exécuté en secret par Nagegetsu — 7ᵉ Mizukage. Yogetsu devint plus tard le 8ᵉ Mizukage. Place ces 5 événements dans l'ordre chronologique strict : (A) Yogetsu devient 8ᵉ Mizukage · (B) Mizugami forme Yogetsu · (C) Mizugami tue Reigetsu · (D) Nagegetsu accède au titre de 7ᵉ Mizukage · (E) Nagegetsu fait exécuter Mizugami en secret.",
    choices: [
      "B → C → D → E → A",
      "C → B → D → E → A",
      "B → D → C → E → A",
      "B → C → E → D → A",
    ],
    answer: 0,
  },
  {
    id: "impossible-paradoxe-brumes-jumelles",
    section: "Paradoxe des Brumes Jumelles",
    diff: 5,
    pts: 20,
    impossible: true,
    q: "Durant une mission diplomatique secrète entre Kiri et Suna, quatre parchemins furent scellés. Exactement deux ninjas disent entièrement vrai, exactement un ment entièrement, et le dernier mélange vérité et mensonge. Le coupable du sabotage n'est ni celui qui ment totalement, ni l'un de ceux qui disent totalement vrai. Parmi Aogami et Raiden, l'un est totalement honnête et l'autre est le coupable. Aucun Hōzuki ne dit le même nombre de vérités. Aogami : « Raiden n'est pas innocent. » / « Tengetsu dit au moins une vérité. » Raiden : « Kyugetsu ment totalement. » / « Aogami est innocent. » Kyugetsu : « Le coupable est plus âgé que moi. » / « Raiden dit entièrement vrai. » Tengetsu : « Kyugetsu ment au moins une fois. » / « Je suis innocent. » Qui est le coupable ?",
    choices: [
      "Aogami Hoshigaki",
      "Kyugetsu Hōzuki",
      "Raiden Karatachi",
      "Tengetsu Hōzuki",
    ],
    answer: 3,
  },
  {
    id: "extra-q8-hozuki-mizukage-negation",
    section: "Logique",
    diff: 2,
    pts: 2,
    q: "Q8. « Il est faux qu'aucun Hōzuki n'ait été Mizukage » signifie :",
    choices: [
      "Aucun Hōzuki n'a été Mizukage",
      "Au moins un Hōzuki a été Mizukage",
      "Tous les Hōzuki ont été Mizukage",
      "Tous les Mizukage ont été Hōzuki",
    ],
    answer: 1,
  },
  {
    id: "extra-q9-yogetsu-regne",
    section: "Chronologie & Successions",
    diff: 2,
    pts: 2,
    q: "Q9. Mizugami fut sensei de Yogetsu. Yogetsu devient 8ᵉ Mizukage. Mizugami fut exécuté en secret par Nagegetsu (7ᵉ). Donc lorsque Yogetsu accède au titre :",
    choices: [
      "Mizugami est encore vivant",
      "Mizugami est mort depuis le règne de Nagegetsu",
      "Yogetsu n'a jamais été formé",
      "On ne peut rien savoir",
    ],
    answer: 1,
  },
  {
    id: "extra-q10-cette-phrase-est-fausse",
    section: "Logique",
    diff: 3,
    pts: 3,
    q: "Q10. Un shinobi déclare : « Cette phrase est fausse. » Conclusion logique :",
    choices: [
      "C'est vrai",
      "C'est faux",
      "Indécidable",
      "Cela prouve qu'il ment",
    ],
    answer: 2,
  },
  {
    id: "extra-q13-mizugami-clan",
    section: "Clans de la Brume",
    diff: 1,
    pts: 1,
    q: "Q13. Mizugami est surnommé « Démon de la Brume ». À quel clan appartient-il ?",
    choices: ["Hōzuki", "Karatachi", "Hoshigaki", "Yokushin"],
    answer: 2,
  },
  {
    id: "extra-q18-brume-sanglante-philosophie",
    section: "Clans de la Brume",
    diff: 2,
    pts: 2,
    q: "Q18. Le clan Hoshigaki dirige l'Académie. La philosophie enseignée est celle de la Brume Sanglante. On peut en déduire que les shinobi de Kiri sont formés à :",
    choices: [
      "La pacification",
      "Une éducation cosmopolite",
      "La prédation et la domination",
      "La pratique exclusive du Genjutsu",
    ],
    answer: 2,
  },
  {
    id: "extra-q20-grands-clans-kiri",
    section: "Clans de la Brume",
    diff: 1,
    pts: 1,
    q: "Q20. Combien de grands clans composent Kirigakure ?",
    choices: ["3", "4", "5", "6"],
    answer: 1,
  },
  {
    id: "extra-q21-assassin-reigetsu",
    section: "Chronologie & Successions",
    diff: 1,
    pts: 1,
    q: "Q21. Qui assassina Reigetsu, 6ᵉ Mizukage ?",
    choices: [
      "Nagegetsu Hōzuki",
      "Mizugami Hoshigaki",
      "Yogetsu Hōzuki",
      "Kazuyori Karatachi",
    ],
    answer: 1,
  },
  {
    id: "extra-q26-suigetsu-mizukage",
    section: "Chronologie & Successions",
    diff: 2,
    pts: 2,
    q: "Q26. Tous les Mizukage Hōzuki finissent en « -getsu ». Si tu rencontres un shinobi nommé Suigetsu, est-il forcément Mizukage ?",
    choices: [
      "Oui, par convention",
      "Non",
      "Oui mais seulement âgé",
      "Non, c'est forcément un imposteur",
    ],
    answer: 1,
  },
  {
    id: "extra-q29-taijutsu-kiri",
    section: "Fondations",
    diff: 1,
    pts: 1,
    q: "Q29. Le Taijutsu est-il un art noble à Kiri ?",
    choices: [
      "Oui, art principal",
      "Non, méprisé",
      "Vrai pour les Hoshigaki uniquement",
      "Réservé aux Mizukage",
    ],
    answer: 1,
  },
  {
    id: "extra-q36-suika-kirisogan",
    section: "Clans de la Brume",
    diff: 1,
    pts: 1,
    q: "Q36. Suika no Jutsu est aux Hōzuki ce que Kirisogan est aux ___",
    choices: ["Hoshigaki", "Yokushin", "Karatachi", "Hōzuki"],
    answer: 2,
  },
  {
    id: "extra-q38-kazuyori-surnom",
    section: "Clans de la Brume",
    diff: 1,
    pts: 1,
    q: "Q38. Mizugami est à « Démon de la Brume » ce que Kazuyori est à ___",
    choices: [
      "« Faucheur de la Brume »",
      "« Sirène aux Mille Échos »",
      "« Traqueur Fantôme »",
      "« Démon de la Brume »",
    ],
    answer: 0,
  },
  {
    id: "extra-q42-kazekage-suna",
    section: "Fondations",
    diff: 1,
    pts: 1,
    q: "Q42. Le Mizukage dirige Kiri. Le Kazekage dirige ___",
    choices: ["Konoha", "Suna", "Kumo", "Iwa"],
    answer: 1,
  },
  {
    id: "extra-q43-hana-no-ken-hanabi",
    section: "Armes & Forges",
    diff: 2,
    pts: 2,
    q: "Q43. Tenshiken est à Tensho ce que Hana no Ken est à ___",
    choices: ["Hanabi", "Shingen", "Karatachi", "Hoshigaki"],
    answer: 0,
  },
  {
    id: "extra-q46-suite-hozuki",
    section: "Chronologie & Successions",
    diff: 2,
    pts: 2,
    q: "Q46. Suite des rangs de Mizukage Hōzuki : 6, 7, 8, ___",
    choices: ["9", "10", "11", "12"],
    answer: 2,
  },
  {
    id: "extra-q47-suite-hoshigaki",
    section: "Chronologie & Successions",
    diff: 2,
    pts: 2,
    q: "Q47. Suite des rangs de Mizukage Hoshigaki : 2, 9, 10, ___",
    choices: ["11", "12", "13", "14"],
    answer: 2,
  },
  {
    id: "extra-q48-suite-karatachi",
    section: "Chronologie & Successions",
    diff: 2,
    pts: 2,
    q: "Q48. Suite des rangs de Mizukage Karatachi : 4, 12, ___",
    choices: ["13", "14", "15", "16"],
    answer: 2,
  },
  {
    id: "extra-q49-art-de-la-parole",
    section: "Fondations",
    diff: 2,
    pts: 2,
    q: "Q49. Niveaux de l'Art de la Parole : Rassemble → Brise → Manipule → ___ → Tue",
    choices: ["Convertit", "Domine", "Libère", "Console"],
    answer: 1,
  },
  {
    id: "extra-q50-mudras-lapin",
    section: "Éléments & Mudrās",
    diff: 2,
    pts: 2,
    q: "Q50. Mudrās : Rat, Bœuf, Tigre, ___, Dragon",
    choices: ["Lapin", "Serpent", "Cheval", "Singe"],
    answer: 0,
  },
  {
    id: "extra-q53-cycle-elementaire-suiton",
    section: "Éléments & Mudrās",
    diff: 2,
    pts: 2,
    q: "Q53. Cycle élémentaire : Katon > Fūton, Fūton > Raiton, Raiton > Doton, Doton > ___, Suiton > Katon",
    choices: ["Doton", "Suiton", "Raiton", "Fūton"],
    answer: 1,
  },
  {
    id: "extra-q54-succession-reigetsu",
    section: "Chronologie & Successions",
    diff: 1,
    pts: 1,
    q: "Q54. Parmi les Mizukage Hōzuki, qui suit immédiatement Reigetsu dans la succession ?",
    choices: ["Suigetsu", "Nagegetsu", "Yogetsu", "Kogetsu"],
    answer: 1,
  },
  {
    id: "extra-q58-feuille-doton",
    section: "Éléments & Mudrās",
    diff: 3,
    pts: 3,
    q: "Q58. Test de la feuille pour 5 shinobi : 1 enflammée, 2 mouillées, 1 coupée en deux, 1 froissée. Combien ont une affinité avec une nature qui bat le Doton ?",
    choices: ["0", "1", "2", "3"],
    answer: 1,
  },
  {
    id: "extra-paires-elements",
    section: "Éléments & Probabilités",
    diff: 2,
    pts: 2,
    q: "Combien de paires distinctes peut-on former parmi les 5 éléments basiques ?",
    choices: ["5", "10", "15", "25"],
    answer: 1,
  },
  {
    id: "extra-proba-mizukage-hozuki",
    section: "Probabilités",
    diff: 2,
    pts: 2,
    q: "Tu choisis aléatoirement un Mizukage parmi les 16. Quelle est la probabilité qu'il soit Hōzuki ?",
    choices: ["1/3", "8/15", "1/2", "4/15"],
    answer: 2,
  },
  {
    id: "extra-q67-loyal-trompeur",
    section: "Logique",
    diff: 3,
    pts: 3,
    q: "Q67. Trois individus A, B, C participent à une épreuve de vérité. Deux profils sont possibles : « Loyal » (dit toujours vrai) et « Trompeur » (ment toujours). A dit : « Je suis Loyal. » B dit : « A est Trompeur. » Que conclure de B ?",
    choices: [
      "B est forcément Loyal",
      "B est forcément Trompeur",
      "B est Loyal si et seulement si A est Trompeur",
      "Impossible à déterminer dans tous les cas",
    ],
    answer: 2,
  },
  {
    id: "extra-q70-yokushin-mizukage",
    section: "Logique",
    diff: 2,
    pts: 2,
    q: "Q70. « Tous les Yokushin servent les Hōzuki. Aucun Yokushin n'est Mizukage. » Si X est Mizukage, on peut conclure :",
    choices: [
      "X sert les Hōzuki",
      "X n'est pas Yokushin",
      "X est forcément Hōzuki",
      "X est forcément Hoshigaki",
    ],
    answer: 1,
  },
  {
    id: "extra-q71-riviere-hoshigaki",
    section: "Logique",
    diff: 4,
    pts: 4,
    q: "Q71. Tu dois traverser une rivière avec trois éléments : un Hoshigaki affamé, un panier de poissons frais, et un parchemin Inton fragile. La barque ne porte qu'un élément à la fois. Sans surveillance : le Hoshigaki dévorerait les poissons ; les poissons abîmeraient le parchemin par humidité. Que prendre en premier ?\n(Le panier est « central » : il est mangé par le Hoshigaki ET abîme le parchemin.)",
    choices: ["Le Hoshigaki", "Le panier de poissons", "Le parchemin", "Impossible"],
    answer: 1,
  },
  {
    id: "extra-prisonniers-bandeaux",
    section: "Logique",
    diff: 4,
    pts: 4,
    q: "Trois prisonniers dans la Fosse Sanglante. Trois bandeaux verts et deux noirs disponibles. P1 voit P2 et P3 mais pas son bandeau, et déclare ne pas savoir. P2 voit P3 mais pas son bandeau, et déclare ne pas savoir. P3 ne voit personne, mais déduit son bandeau. Quelle est sa couleur ?",
    choices: ["Vert", "Noir", "Indécidable", "Mixte"],
    answer: 0,
  },
  {
    id: "extra-pont-17-minutes",
    section: "Logique",
    diff: 4,
    pts: 4,
    q: "Quatre shinobi doivent traverser un pont en moins de 17 minutes. Le pont supporte 2 personnes à la fois et exige une seule lanterne. Temps individuels : Shū 1 min, Mizugami 2 min, Yogetsu 5 min, Habizumo 10 min. Temps total minimal ?",
    choices: ["17 minutes exactement", "18 minutes", "20 minutes", "Impossible"],
    answer: 0,
  },
  {
    id: "extra-senbon-empoisonnee",
    section: "Logique",
    diff: 4,
    pts: 4,
    q: "Tu disposes de 1000 senbon dont une seule est empoisonnée. Le poison agit en 24 heures. Combien de prisonniers minimum dois-tu mobiliser pour identifier la senbon empoisonnée avant l'échéance ?",
    choices: ["10", "31", "100", "500"],
    answer: 0,
  },
  {
    id: "extra-marques-rouges",
    section: "Logique",
    diff: 4,
    pts: 4,
    q: "Trois candidats Mizukage reçoivent chacun une marque sur le front : rouge ou bleue. On leur annonce qu'il y a au moins une marque rouge. Chacun voit les autres mais pas la sienne. À chaque tour, ils déclarent « rouge » s'ils en sont certains. Personne ne parle au tour 1 ni au tour 2. Au tour 3, tous trois disent « rouge » simultanément. Combien y avait-il de rouges au total ?",
    choices: ["1", "2", "3", "Indéterminable"],
    answer: 2,
  },
  {
    id: "extra-q80-sage-sortie",
    section: "Logique",
    diff: 4,
    pts: 4,
    q: "Q80. Tu fais face à trois portes : l'une mène à la sortie, les deux autres à la Fosse Sanglante. Un sage présent dit toujours le contraire de la vérité. Une question oui/non possible. Comment t'assurer de trouver la sortie ?",
    choices: [
      "« Cette porte mène-t-elle à la sortie ? »",
      "« Es-tu un sage ? »",
      "« Si je te demandais si cette porte mène à la sortie, répondrais-tu oui ? »",
      "« Y a-t-il une sortie ? »",
    ],
    answer: 2,
  },
  {
    id: "extra-q81-kanji-eau",
    section: "Reconnaissance & Symboles",
    diff: 1,
    pts: 1,
    q: "Q81. Le kanji 水 signifie :",
    choices: ["Eau", "Feu", "Vent", "Terre"],
    answer: 0,
  },
  {
    id: "extra-q82-kanji-katon",
    section: "Reconnaissance & Symboles",
    diff: 1,
    pts: 1,
    q: "Q82. Lequel de ces kanji représente le Katon ?",
    choices: ["水", "火", "風", "雷"],
    answer: 1,
  },
  {
    id: "extra-q83-kanji-raiton",
    section: "Reconnaissance & Symboles",
    diff: 1,
    pts: 1,
    q: "Q83. Lequel de ces kanji représente le Raiton ?",
    choices: ["水", "火", "風", "雷"],
    answer: 3,
  },
  {
    id: "extra-q84-dragon-mudra",
    section: "Reconnaissance & Symboles",
    diff: 2,
    pts: 2,
    q: "Q84. Le mudrā du Dragon (Tatsu) symbolise :",
    choices: [
      "Vitesse et ruse",
      "Équilibre mystique et union des contraires",
      "Force brute",
      "Instinct animal",
    ],
    answer: 1,
  },
  {
    id: "extra-q85-kusarigama-reconnaissance",
    section: "Reconnaissance & Symboles",
    diff: 1,
    pts: 1,
    q: "Q85. Une arme hybride : chaîne reliée à une faucille, maillons enduits de poison. Que reconnais-tu ?",
    choices: ["Saya Naginata", "Lame Noire", "Kusarigama", "Tantō"],
    answer: 2,
  },
  {
    id: "extra-q86-liquefaction-clan",
    section: "Reconnaissance & Symboles",
    diff: 1,
    pts: 1,
    q: "Q86. Un shinobi liquéfie son corps entier en eau pure, défiant la torture. À quel clan appartient-il ?",
    choices: ["Hoshigaki", "Karatachi", "Hōzuki", "Yokushin"],
    answer: 2,
  },
  {
    id: "extra-q87-citation-hoshigaki",
    section: "Reconnaissance & Symboles",
    diff: 2,
    pts: 2,
    q: "Q87. Citation : « Si tu es faible, tu te tais. Si tu es fort, tu déchires. » De quel clan provient-elle ?",
    choices: ["Hōzuki", "Karatachi", "Hoshigaki", "Yokushin"],
    answer: 2,
  },
  {
    id: "extra-q88-hana-no-ken",
    section: "Reconnaissance & Symboles",
    diff: 1,
    pts: 1,
    q: "Q88. Énorme épée gravée de pétales dont chaque coupe disperse des éclats de chakra en forme de pétales. Quelle lame ?",
    choices: ["Tenshiken", "Hana no Ken", "Nozarashi", "Saya Naginata"],
    answer: 1,
  },
  {
    id: "extra-q89-tora-katon",
    section: "Reconnaissance & Symboles",
    diff: 2,
    pts: 2,
    q: "Q89. Un shinobi joint les doigts en Tigre (Tora). Selon la symbolique des mudrās, quelle nature de chakra évoque-t-il principalement ?\n(Tora = flamme, force, colère.)",
    choices: ["Suiton", "Doton", "Katon", "Fūton"],
    answer: 2,
  },
  {
    id: "extra-q90-shakuton",
    section: "Reconnaissance & Symboles",
    diff: 2,
    pts: 2,
    q: "Q90. Un médecin-ninja attaque sans contact en faisant évaporer les fluides corporels de sa cible. Quelle nature de chakra utilise-t-il ?",
    choices: ["Yōton", "Shakuton", "Futton", "Suiton"],
    answer: 1,
  },
  {
    id: "extra-q91-orientation-sud",
    section: "Orientation & Hiérarchie",
    diff: 2,
    pts: 2,
    q: "Q91. Tu es face au nord. Tu tournes 90° à droite, puis 180°, puis 90° à gauche. Tu fais face à :",
    choices: ["Nord", "Sud", "Est", "Ouest"],
    answer: 1,
  },
  {
    id: "extra-q92-zone-abyssale",
    section: "Orientation & Hiérarchie",
    diff: 1,
    pts: 1,
    q: "Q92. Tu descends de la Zone Lumineuse à la Zone Crépusculaire. Pour atteindre la Zone Abyssale, tu dois :",
    choices: [
      "Remonter vers la surface",
      "Continuer à descendre",
      "Rester au même niveau",
      "Sortir et entrer ailleurs",
    ],
    answer: 1,
  },
  {
    id: "extra-q93-kazuyori-avant-shu",
    section: "Orientation & Hiérarchie",
    diff: 1,
    pts: 1,
    q: "Q93. Sur une ligne du temps des Mizukage de 1 à 15, où se situe Kazuyori  par rapport à Shû  ?",
    choices: ["Avant", "Après", "Simultanément", "Indéterminable"],
    answer: 0,
  },
  {
    id: "extra-q94-mizukage-vs-main",
    section: "Orientation & Hiérarchie",
    diff: 1,
    pts: 1,
    q: "Q94. Dans la hiérarchie de Kiri, qui occupe le rang le plus élevé : le Mizukage ou la Main du Mizukage ?",
    choices: ["Le Mizukage", "La Main", "Égalité", "Deux chefs égaux"],
    answer: 0,
  },
  {
    id: "extra-q95-hozuki-vs-yokushin",
    section: "Orientation & Hiérarchie",
    diff: 1,
    pts: 1,
    q: "Q95. Dans la hiérarchie sociale traditionnelle de Kiri, qui est placé plus haut : un Hōzuki ou un Yokushin ?",
    choices: ["Hōzuki", "Yokushin", "Égaux", "Cela dépend des circonstances"],
    answer: 0,
  },
  {
    id: "extra-q96-syllogisme",
    section: "Logique",
    diff: 1,
    pts: 1,
    q: "Q96. Si tous les A sont B, et tous les B sont C, alors :",
    choices: [
      "Tous les A sont C",
      "Tous les C sont A",
      "Aucun A n'est C",
      "Certains A ne sont pas C",
    ],
    answer: 0,
  },
  {
    id: "extra-q97-au-moins-une-face",
    section: "Probabilités",
    diff: 3,
    pts: 3,
    q: "Q97. Une pièce est lancée 3 fois. Quelle est la probabilité d'obtenir au moins une face ?",
    choices: ["50%", "75%", "87,5%", "100%"],
    answer: 2,
  },
  {
    id: "extra-q98-feuille-epaisseurs",
    section: "Logique",
    diff: 2,
    pts: 2,
    q: "Q98. Tu plies une feuille en deux trois fois de suite. Combien d'épaisseurs obtiens-tu ?",
    choices: ["4", "6", "8", "16"],
    answer: 2,
  },
  {
    id: "extra-q99-des-somme-7",
    section: "Probabilités",
    diff: 3,
    pts: 3,
    q: "Q99. Tu lances 2 dés à 6 faces. Quelle est la probabilité d'obtenir un total de 7 ?",
    choices: ["1/12", "1/6", "1/8", "1/4"],
    answer: 1,
  },
  {
    id: "extra-q100-hasard-4-choix",
    section: "Probabilités",
    diff: 1,
    pts: 1,
    q: "Q100. Cette question propose 4 choix, un seul correct. En répondant au hasard, quelle est ta probabilité d'avoir juste ?",
    choices: ["25%", "33%", "50%", "100%"],
    answer: 0,
  },
  {
    id: "extra-photo-fils",
    section: "Logique",
    diff: 2,
    pts: 2,
    q: "Un homme regarde une photo et dit : « Je n’ai ni frère ni sœur, mais le père de cet homme est le fils de mon père. » Qui est sur la photo ?",
    choices: ["Son fils.", "Son père.", "Son cousin.", "Lui-même."],
    answer: 0,
  },
  {
    id: "extra-deux-peres-deux-fils",
    section: "Logique",
    diff: 2,
    pts: 2,
    q: "Deux pères et deux fils vont à la pêche. Ils attrapent trois poissons, et chacun en reçoit un. Comment est-ce possible ?",
    choices: [
      "Ils ont menti sur le nombre de poissons.",
      "Il s’agit de trois personnes seulement.",
      "L’un des pères n’est pas humain.",
      "Ils ont partagé un poisson en morceaux.",
    ],
    answer: 1,
  },
  {
    id: "extra-combien-de-9",
    section: "Logique",
    diff: 3,
    pts: 3,
    q: "Combien de fois le chiffre 9 apparaît-il de 1 à 100 ?",
    choices: ["10.", "19.", "20.", "21."],
    answer: 2,
  },
  {
    id: "extra-enterrer-survivants",
    section: "Logique",
    diff: 1,
    pts: 1,
    q: "Une bataille a lieu entre Suna et Kiri, ou enterre-t-on les survivants ?",
    choices: ["Suna", "Kiri", "À la frontière.", "Nul part"],
    answer: 3,
  },
];

export const LEGACY_QUESTION_IDS = [
  "foundation-suiton-reine",
  "foundation-monde-invisible",
  "foundation-mudras-majeurs",
  "weapons-saya-tensho",
  "weapons-lame-noire-nature",
  "weapons-jashin-faux-activation",
  "weapons-kusarigama-forgeur",
  "weapons-nozarashi",
  "weapons-jashin-double-action",
  "clans-hozuki-suika",
  "clans-karatachi-kirisogan",
  "clans-academie-hoshigaki",
  "clans-yokushin-hozuki",
  "clans-hoshigaki-requins-blancs",
  "clans-kazuyori-rang",
  "genjutsu-zone-crepusculaire",
  "genjutsu-fuinjutsu-piliers",
  "genjutsu-shakuton-douleur",
  "reasoning-kuroi-kaminari",
  "reasoning-mugen-karatachi",
  "reasoning-habizumo-prothese",
  "finale-mizugami-chronologie",
  "impossible-paradoxe-brumes-jumelles",
];

const QUESTION_MAP = new Map(QUESTION_BANK.map((question) => [question.id, question]));

export function getQuestionById(id) {
  return QUESTION_MAP.get(id) || null;
}

export function getQuestionSetByIds(ids) {
  if (!Array.isArray(ids)) {
    return [];
  }

  return ids.map((id) => getQuestionById(id)).filter(Boolean);
}

export function getLegacyQuestions() {
  return getQuestionSetByIds(LEGACY_QUESTION_IDS);
}

export function getQuestionStats(questions) {
  const normalizedQuestions = Array.isArray(questions) ? questions : [];
  const normalQuestions = normalizedQuestions.filter((question) => !question.impossible);

  return {
    totalMax: normalizedQuestions.reduce((sum, question) => sum + question.pts, 0),
    normalMax: normalQuestions.reduce((sum, question) => sum + question.pts, 0),
    normalQuestionCount: normalQuestions.length,
    impossibleIndex: normalizedQuestions.findIndex((question) => question.impossible),
  };
}

function shuffleQuestions(questions, random = Math.random) {
  const copy = [...questions];

  for (let index = copy.length - 1; index > 0; index -= 1) {
    const randomIndex = Math.floor(random() * (index + 1));
    [copy[index], copy[randomIndex]] = [copy[randomIndex], copy[index]];
  }

  return copy;
}

export function pickQuestionSet(random = Math.random) {
  const impossibleQuestions = QUESTION_BANK.filter((question) => question.impossible);
  const normalQuestions = QUESTION_BANK.filter((question) => !question.impossible);
  const impossibleCount = Math.min(impossibleQuestions.length, 1);
  const normalCount = Math.min(
    normalQuestions.length,
    Math.max(0, TEST_QUESTION_COUNT - impossibleCount)
  );
  const chosenNormal = shuffleQuestions(normalQuestions, random).slice(0, normalCount);
  const chosenImpossible = shuffleQuestions(impossibleQuestions, random).slice(
    0,
    TEST_QUESTION_COUNT - chosenNormal.length
  );

  return [...chosenNormal, ...chosenImpossible];
}
